# Generated by Django 3.2.7 on 2021-10-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210929_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproduct',
            options={'ordering': ('-created',), 'verbose_name_plural': 'NewProducts'},
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
        migrations.AddField(
            model_name='newproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newproduct', to='product.category'),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'Jamais utilisé'), ('good', 'Bon état'), ('used', 'Moyen')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='n_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='r_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='specs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
