# Generated by Django 3.2.7 on 2021-10-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211003_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
