# Generated by Django 3.2.7 on 2021-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_newproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_newproduct',
            field=models.BooleanField(default=False),
        ),
    ]
