# Generated by Django 3.2.7 on 2021-10-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_visits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
