# Generated by Django 3.2.7 on 2021-10-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_num_visits_product_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userip',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='visits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
