# Generated by Django 3.2.7 on 2021-10-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20211006_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
