# Generated by Django 3.2.7 on 2021-09-23 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Normal_User', 'Normal_User'), ('Revendeur', 'Revendeur')], max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('passwd', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('modified_at', models.TimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
