# Generated by Django 3.2.7 on 2021-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='typeuser',
            field=models.CharField(choices=[('Normal_User', 'Normal_User'), ('Revendeur', 'Revendeur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
