# Generated by Django 3.2.7 on 2021-09-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210925_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
