# Generated by Django 3.2.7 on 2021-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210926_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_normal',
            field=models.BooleanField(default=False, verbose_name='Is normal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_revendeur',
            field=models.BooleanField(default=False, verbose_name='Is revendeur'),
        ),
    ]
