# Generated by Django 3.2.7 on 2021-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211003_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_normal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_revendeur',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Revendeur',
            field=models.BooleanField(default=False, verbose_name='Revendeur'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Utilisateur_normal',
            field=models.BooleanField(default=False, verbose_name='Utilisateur normal'),
        ),
    ]
