# Generated by Django 3.2.7 on 2021-10-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211003_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Utilisateur_normal',
            new_name='Is_normal',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Revendeur',
            new_name='Is_revendeur',
        ),
    ]
