# Generated by Django 3.2.7 on 2021-10-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211003_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Is_normal',
            field=models.BooleanField(default=True, verbose_name='Utilisateur normal'),
        ),
    ]
