# Generated by Django 3.2.7 on 2021-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_is_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Is_normal',
            field=models.BooleanField(default=False, verbose_name='Utilisateur normal'),
        ),
    ]
