# Generated by Django 3.2.7 on 2021-10-06 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_alter_userprofile_is_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Is_normal',
            field=models.BooleanField(default=True, verbose_name='Utilisateur normal'),
        ),
        migrations.CreateModel(
            name='UserProfileR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('Is_normal', models.BooleanField(default=False, verbose_name='Utilisateur normal')),
                ('Is_revendeur', models.BooleanField(default=True, verbose_name='Revendeur')),
                ('Is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
