# Generated by Django 3.2.7 on 2021-10-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20211007_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiler',
            options={'verbose_name_plural': 'Revendeur user profiles'},
        ),
    ]
