# Generated by Django 3.2.7 on 2021-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userprofiler_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Is_normal',
            field=models.BooleanField(default=False, verbose_name='Utilisateur normal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Is_revendeur',
            field=models.BooleanField(default=True, verbose_name='Revendeur'),
        ),
        migrations.DeleteModel(
            name='UserProfileR',
        ),
    ]
